[theme]
primaryColor = "#1d9bf0"
backgroundColor = "#08090b"
secondaryBackgroundColor = "#13171c"
textColor = "#e7e9ea"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
